<?php

return [
    'color' => [
        'yellow' => [
            'label' => 'Yellow',
            'swatch' => '#fed700',
            'primary' => '#fed700',
            'secondary' => '#2a3746',
            'accent' => '#f5f5f5',
            'res' => '#333e48',
            'bg' => '#f8f8f8',
            'dynamic' => '#ddd',
            'heading' => '#7c7c7c',
            'permanent' => '#eaeaea',
            'text' => '#7c7c7c',
        ],
        'red' => [
            'label' => 'Red',
            'swatch' => '#e53935',
            'primary' => '#e53935',
            'secondary' => '#2a3746',
            'accent' => '#f5f5f5',
            'res' => '#333e48',
            'bg' => '#f8f8f8',
            'dynamic' => '#ddd',
            'heading' => '#7c7c7c',
            'permanent' => '#eaeaea',
            'text' => '#7c7c7c',
        ],
        'blue' => [
            'label' => 'Blue',
            'swatch' => '#1e88e5',
            'primary' => '#1e88e5',
            'secondary' => '#2a3746',
            'accent' => '#f5f5f5',
            'res' => '#333e48',
            'bg' => '#f8f8f8',
            'dynamic' => '#ddd',
            'heading' => '#7c7c7c',
            'permanent' => '#eaeaea',
            'text' => '#7c7c7c',
        ],
        'green' => [
            'label' => 'Green',
            'swatch' => '#43a047',
            'primary' => '#43a047',
            'secondary' => '#2a3746',
            'accent' => '#f5f5f5',
            'res' => '#333e48',
            'bg' => '#f8f8f8',
            'dynamic' => '#ddd',
            'heading' => '#7c7c7c',
            'permanent' => '#eaeaea',
            'text' => '#7c7c7c',
        ],
        'purple' => [
            'label' => 'Purple',
            'swatch' => '#7c4dff',
            'primary' => '#7c4dff',
            'secondary' => '#2a3746',
            'accent' => '#f5f5f5',
            'res' => '#333e48',
            'bg' => '#f8f8f8',
            'dynamic' => '#ddd',
            'heading' => '#7c7c7c',
            'permanent' => '#eaeaea',
            'text' => '#7c7c7c',
        ],
        'orange' => [
            'label' => 'Orange',
            'swatch' => '#fb8c00',
            'primary' => '#fb8c00',
            'secondary' => '#2a3746',
            'accent' => '#f5f5f5',
            'res' => '#333e48',
            'bg' => '#f8f8f8',
            'dynamic' => '#ddd',
            'heading' => '#7c7c7c',
            'permanent' => '#eaeaea',
            'text' => '#7c7c7c',
        ],
        'pink' => [
            'label' => 'Pink',
            'swatch' => '#d81b60',
            'primary' => '#d81b60',
            'secondary' => '#2a3746',
            'accent' => '#f5f5f5',
            'res' => '#333e48',
            'bg' => '#f8f8f8',
            'dynamic' => '#ddd',
            'heading' => '#7c7c7c',
            'permanent' => '#eaeaea',
            'text' => '#7c7c7c',
        ],
        'teal' => [
            'label' => 'Teal',
            'swatch' => '#00897b',
            'primary' => '#00897b',
            'secondary' => '#2a3746',
            'accent' => '#f5f5f5',
            'res' => '#333e48',
            'bg' => '#f8f8f8',
            'dynamic' => '#ddd',
            'heading' => '#7c7c7c',
            'permanent' => '#eaeaea',
            'text' => '#7c7c7c',
        ],
    ],
    'backend-color' => [
        'purple' => [
            'label' => 'Purple',
            'swatch' => '#7367f0',
            'primary' => '#7367f0',
            'secondary' => '#7983a7',
            'accent' => '#2f3349',
            'res' => '#b6bee3',
            'bg' => '#25293c',
            'dynamic' => '#3a3d53',
            'heading' => '#d0d4f1',
            'permanent' => '#434968',
        ],
        'red' => [
            'label' => 'Red',
            'swatch' => '#ea5455',
            'primary' => '#ea5455',
            'secondary' => '#7983a7',
            'accent' => '#2f3349',
            'res' => '#b6bee3',
            'bg' => '#25293c',
            'dynamic' => '#3a3d53',
            'heading' => '#d0d4f1',
            'permanent' => '#434968',
        ],
        'blue' => [
            'label' => 'Blue',
            'swatch' => '#1e88e5',
            'primary' => '#1e88e5',
            'secondary' => '#7983a7',
            'accent' => '#2f3349',
            'res' => '#b6bee3',
            'bg' => '#25293c',
            'dynamic' => '#3a3d53',
            'heading' => '#d0d4f1',
            'permanent' => '#434968',
        ],
        'green' => [
            'label' => 'Green',
            'swatch' => '#28c76f',
            'primary' => '#28c76f',
            'secondary' => '#7983a7',
            'accent' => '#2f3349',
            'res' => '#b6bee3',
            'bg' => '#25293c',
            'dynamic' => '#3a3d53',
            'heading' => '#d0d4f1',
            'permanent' => '#434968',
        ],
        'orange' => [
            'label' => 'Orange',
            'swatch' => '#ff9f43',
            'primary' => '#ff9f43',
            'secondary' => '#7983a7',
            'accent' => '#2f3349',
            'res' => '#b6bee3',
            'bg' => '#25293c',
            'dynamic' => '#3a3d53',
            'heading' => '#d0d4f1',
            'permanent' => '#434968',
        ],
        'yellow' => [
            'label' => 'Yellow',
            'swatch' => '#ffc107',
            'primary' => '#ffc107',
            'secondary' => '#7983a7',
            'accent' => '#2f3349',
            'res' => '#b6bee3',
            'bg' => '#25293c',
            'dynamic' => '#3a3d53',
            'heading' => '#d0d4f1',
            'permanent' => '#434968',
        ],
        'pink' => [
            'label' => 'Pink',
            'swatch' => '#ff4c51',
            'primary' => '#ff4c51',
            'secondary' => '#7983a7',
            'accent' => '#2f3349',
            'res' => '#b6bee3',
            'bg' => '#25293c',
            'dynamic' => '#3a3d53',
            'heading' => '#d0d4f1',
            'permanent' => '#434968',
        ],
        'teal' => [
            'label' => 'Teal',
            'swatch' => '#00bad1',
            'primary' => '#00bad1',
            'secondary' => '#7983a7',
            'accent' => '#2f3349',
            'res' => '#b6bee3',
            'bg' => '#25293c',
            'dynamic' => '#3a3d53',
            'heading' => '#d0d4f1',
            'permanent' => '#434968',
        ],
    ],
];
