/**
 * Sample product data for local development and component previews.
 * @type {import('./types').Product[]}
 */
export const MOCK_PRODUCTS = [
    {
        id: 1,
        title: 'Samsung Galaxy S25 Ultra',
        image: '/assets/image/samsung-galaxy-s25-ultra-12gb-256gb-pakistan-priceoye-f5qk5-500x500.webp',
        price: 429999,
        originalPrice: 459999,
        rating: 4.8,
        reviewCount: 128,
        currency: 'PKR',
    },
    {
        id: 2,
        title: 'Galaxy Buds Pro 3',
        image: '/assets/image/mobiles.webp',
        price: 34999,
        originalPrice: null,
        rating: 4.5,
        reviewCount: 64,
        currency: 'PKR',
    },
    {
        id: 3,
        title: 'Galaxy Watch Ultra',
        image: '/assets/image/samsung-galaxy-s25-ultra-12gb-256gb-pakistan-priceoye-h0km1-500x500.webp',
        price: 89999,
        originalPrice: 94999,
        rating: 4.6,
        reviewCount: 42,
        currency: 'PKR',
    },
    {
        id: 4,
        title: 'Galaxy Tab S10',
        image: '/assets/image/samsung-galaxy-s25-ultra-12gb-256gb-pakistan-priceoye-kjqq6-500x500.webp',
        price: 189999,
        originalPrice: null,
        rating: 4.4,
        reviewCount: 31,
        currency: 'PKR',
    },
    {
        id: 5,
        title: 'Galaxy A55 5G',
        image: '/assets/image/samsung-galaxy-s25-ultra-12gb-256gb-pakistan-priceoye-n4y7m-500x500.webp',
        price: 119999,
        originalPrice: 129999,
        rating: 4.3,
        reviewCount: 89,
        currency: 'PKR',
    },
    {
        id: 6,
        title: 'Galaxy Z Fold 6',
        image: '/assets/image/samsung-galaxy-s25-ultra-12gb-256gb-pakistan-priceoye-sh46r-500x500.webp',
        price: 549999,
        originalPrice: null,
        rating: 4.7,
        reviewCount: 17,
        currency: 'PKR',
    },
    {
        id: 7,
        title: 'Galaxy S24 FE',
        image: '/assets/image/samsung-galaxy-s25-ultra-12gb-256gb-pakistan-priceoye-v7sz0-500x500.webp',
        price: 219999,
        originalPrice: 239999,
        rating: 4.2,
        reviewCount: 55,
        currency: 'PKR',
    },
    {
        id: 8,
        title: 'Galaxy Ring',
        image: '/assets/image/samsung-galaxy-s25-ultra-12gb-256gb-pakistan-priceoye-xku3z-500x500.webp',
        price: 74999,
        originalPrice: null,
        rating: 4.1,
        reviewCount: 23,
        currency: 'PKR',
    },
];
